# Generated by Django 4.1 on 2022-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student", name="chinese", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="student", name="english", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student", name="math", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student", name="science", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student", name="society", field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(name="Grade",),
    ]
