# Generated by Django 4.1 on 2022-08-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_student_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(
                choices=[("男", "男"), ("女", "女")], default="男", max_length=150
            ),
        ),
    ]
