# Generated by Django 4.1 on 2022-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_student_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
