# Generated by Django 4.1 on 2022-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_student_total_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="average_score",
            field=models.IntegerField(default=0),
        ),
    ]
