# Generated by Django 4.1 on 2022-08-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_student_average_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="average_score",
            field=models.FloatField(default=0),
        ),
    ]
