# Generated by Django 4.1 on 2022-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_student_average_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.CharField(
                choices=[
                    ("111-1", "111學年度 上學期"),
                    ("111-2", "111學年度 下學期"),
                    ("112-1", "112學年度 上學期"),
                    ("112-2", "112學年度 下學期"),
                ],
                default="111-1",
                max_length=150,
            ),
        ),
    ]
