# Generated by Django 4.1 on 2022-09-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_student_semester"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="semester",),
    ]
